### ISSUE TITLE
Why you put two "elif dataset == 'reduced'":

### ISSUE THREAD

**Issue by leoozy** [VDIGPKU/DADA#19]
Hello, thank you for your excellent work. I noticed that there are two `elif dataset == 'reduced_imagenet':` in your dataset.py. It means that if you run this code, the second elif will not work. Is this an mistake.

**Comment by latstars** [comment]
I think you can use the first reduced_imagenet. The second reduced_imagenet does not matter the first reduced_imagenet. The second reduced_imagenet is just for reference when modifying the code.

**Comment by leoozy** [comment]
Thank you
