### ISSUE TITLE
Extract the found policy

### ISSUE THREAD

**Issue by belkhir-nacim** [VDIGPKU/DADA#9]
Hi,
After checking and testing the code, I am looking a way to extract the found policy.

Also can you explain how we can reuse the found policy.

**Comment by latstars** [comment]
The found policy is displayed in the console, named as genotype. You can also find it in the log file.

**Comment by belkhir-nacim** [comment]
sorry for my late answer, 
Thank you.
I suppose for using it we just copy past it, instead of the genotype variable in the training?

**Comment by latstars** [comment]
> sorry for my late answer,
> Thank you.
> I suppose for using it we just copy past it, instead of the genotype variable in the training?

Yes.

**Comment by belkhir-nacim** [comment]
Thanks!
By the way ,  I really appreciated this work!
